// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVZLJ4ZUuU2_Um-AABTuWtx82B7GG3mBM',
    appId: '1:957464245204:web:a82f4e55d7a57abc6c5c41',
    messagingSenderId: '957464245204',
    projectId: 'event-app-8cb66',
    authDomain: 'event-app-8cb66.firebaseapp.com',
    storageBucket: 'event-app-8cb66.firebasestorage.app',
    measurementId: 'G-CGPT7LZJVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlx2J5X2ABKs1hCu4xQCd6fqf8vSC7Kfk',
    appId: '1:957464245204:android:fb7f1b60c1a5df206c5c41',
    messagingSenderId: '957464245204',
    projectId: 'event-app-8cb66',
    storageBucket: 'event-app-8cb66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslzQmGO3mYVWmruIU3mimAfOKDpdRgfA',
    appId: '1:957464245204:ios:96bcedffcb9e33cb6c5c41',
    messagingSenderId: '957464245204',
    projectId: 'event-app-8cb66',
    storageBucket: 'event-app-8cb66.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCslzQmGO3mYVWmruIU3mimAfOKDpdRgfA',
    appId: '1:957464245204:ios:96bcedffcb9e33cb6c5c41',
    messagingSenderId: '957464245204',
    projectId: 'event-app-8cb66',
    storageBucket: 'event-app-8cb66.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVZLJ4ZUuU2_Um-AABTuWtx82B7GG3mBM',
    appId: '1:957464245204:web:8f468b296ed4885b6c5c41',
    messagingSenderId: '957464245204',
    projectId: 'event-app-8cb66',
    authDomain: 'event-app-8cb66.firebaseapp.com',
    storageBucket: 'event-app-8cb66.firebasestorage.app',
    measurementId: 'G-EMS227KRXV',
  );
}
